### ISSUE TITLE
#!Heal consumes potion without actually healing

### ISSUE THREAD

**Issue by MiloMM** [Sven65/RPGBot#1]
title

**Comment by Sven65** [comment]
I am aware of the bug and I'm doing all I can to fix it.

**Comment by MiloMM** [comment]
Thanks :+1:

**Comment by Sven65** [comment]
Issue has been resolved. Sorry for the inconveniece.

**Comment by MiloMM** [comment]
No problem, just trying to help :)

**Comment by Sven65** [comment]
Thanks. All help and bug reports are appreciated.
